### ISSUE TITLE
Expose pod locality

### ISSUE THREAD

**Issue by tomclement** [ThoughtWorks-DPS/hello-restful#3]
## Desired change
Expose the locality of the pod derived from the platform on which it is running (AWS, GCP, Minikube etc).

## Example
For pods running on a service mesh, there is typically metadata that is exposed by the mesh that includes the details of the locality of the pod. For example, for a pod running on AWS with istio, the envoy sidecar will have the following values available at `http://localhost:15000/config_dump?resource=&mask=&name_regex=`:

```json
"locality": {
"region": "us-east-2",
"zone": "us-east-2c"
}
```

**Comment by tomclement** [comment]
Added the above enhancement in commits #https://github.com/ThoughtWorks-DPS/hello-restful/commit/f576487f5336cd218ebf85b006221976e4a080b2, https://github.com/ThoughtWorks-DPS/hello-restful/commit/ff90c07da170f8f8737b7f67e4054023b40012cd, https://github.com/ThoughtWorks-DPS/hello-restful/commit/60df7f19be0db7d2927d75e7e2155ccdca1c1858

New endpoint is now available at `BASE_URL/v1/hello/server/locality` and returns the following responses:
1. When server information is available:
```json
{
  "region": "region (eg us-east-2)",
  "zone": "zone (eg us-east-2c)",
  "sub_zone": "sub_zone (eg rack-1)" # not applicable for kubernetes
}
```
2. When server information cannot be queried:
```json
{
  "message": "Unable to query server information"
}
```

Locality information is obtained by querying the envoy sidecar `server_info` endpoint available at `http://localhost:15000/server_info`

**Comment by ncheneweth** [comment]
Do we feel confident that continued use of the `server` construct is a good plan? e.g., probably a holdover from the notion that an app is running on a server. In this case we get back node info, which is what we want, and we expect it to be ephemeral in the sense that If I query the service repeated I fully expect I may get a different answer every time based on LB, and I may bet new answers based on l8s orchestration/scaling/etc. - But regardless, the model of is being the "server" is the one we want to persist?

**Comment by tomclement** [comment]
The use of `server` seemed appropriate since Envoy uses the same terminology (as indicated by their naming of the endpoint that is queried for this information - see [here](https://www.envoyproxy.io/docs/envoy/latest/operations/admin#get--server_info)). However, I do agree that this may be more of a hold-over than an appropriate construct for the reasons you mentioned.

One option I considered was to simply expose this information at the endpoint `BASE_URL/v1/hello/locality` since that's currently all that's being returned. However I figure it would be helpful to have some sort of umbrella path in case we decide to return more "server-like" (or I guess in this case "node-like") information in the future.

Another option is to simply change the path to be `BASE_URL/v1/hello/node/locality`. Thoughts?

**Comment by ncheneweth** [comment]
I like Node.

Other thoughts: At the moment, the endpoint is dependent on Istio to provide the info. Therefore we are doing a query against a proxy. e.g., we are returning what the envoy sidecar to a given pod 'thinks' is the current node info. What if it is wrong? Hence, we could put it behind `hello/envoy/locality` and /envoy itself, if it evolves further, remains limited to envoy data.

Envoy could also be used independent of istio (just as general proxy, like where we might otherwise use nginx). You could argue that `/istio/envoy/locality` is more accurate, but that may be a bit pedantic.

**Comment by tomclement** [comment]
Noted. If we want to be that specific then I suggest we go with `/istio/envoy` and change the response payload to include `locality` as a key instead (see example below):
```json
{
  "locality": {
    "region": "region (eg us-east-2)",
    "zone": "zone (eg us-east-2c)",
    "sub_zone": "sub_zone (eg rack-1)"
  }
}
```
